export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const REMOVE_TO_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const SUBMIT_SHIPPING_INFO_FAILURE = "SUBMIT_SHIPPING_INFO_FAILURE";
